### ISSUE TITLE
在 node >=18.16.0 版本以上使用 apmjs 安装依赖包文件内容有错误

### ISSUE THREAD

**Issue by Sheetaa** [apmjs/apmjs#28]
复现版本：
- node：18.16.0
- apmjs：3.2.4

执行 apmjs install @vusa/runtime，到 amd_modules/@vusa/runtime 下查看 vusa.js 文件内容有问题：
![image](https://github.com/apmjs/apmjs/assets/4032009/ae38cfb7-4aa3-4b90-b89b-7806db08106a)

尝试 node 其它版本，发现在 node <18.16版本 apmjs 安装没问题，在 node >=18.16版本 apmjs 安装有问题。
如果使用 npm 安装所有版本下都没有问题。

排查发现 apmjs 依赖了一个解压库 tarball-extract，这个库依赖了 node 内置模块 zlib，使用的 zlib.createGunzip() 方法有问题，用其它相似功能的 gunzip 库替换这行代码验证正常。
![image](https://github.com/apmjs/apmjs/assets/4032009/717447b2-4762-4372-8680-214e67ffedc0)

排查代码：
![image](https://github.com/apmjs/apmjs/assets/4032009/cfb553ae-8572-4690-acdf-31024cdf9557)

建议和 npm 一样使用 pacote.extract 方法替换问题代码，修复这个问题

**Comment by Sheetaa** [comment]
急！准备提个 pr，但是 npm test 有大量报错，我估计是 node 版本差太多导致的不兼容，可以反馈一下你当时开发的时候 node 版本？ @harttle

**Comment by harttle** [comment]
从这里看是 5
https://github.com/apmjs/apmjs/blob/master/.travis.yml

**Comment by Sheetaa** [comment]
合入了，帮忙发个包 @harttle
