### ISSUE TITLE
node 4.5.0安装后运行失败，建议在readme中标注最低node版本

### ISSUE THREAD

**Issue by jennyliang220** [apmjs/apmjs#4]
![image](https://user-images.githubusercontent.com/8498677/31492141-5390b9a2-af7c-11e7-9305-831e9f29c84b.png)

本机node有多个版本node，切换到8.5.0运行`ampjs -v`可以正确返回版本号。建议在readme中标注最低node版本。

**Comment by xuexb** [comment]
本地 node v5.0.0 安装 apmjs@2.0.4 成功~

**Comment by harttle** [comment]
Closing, thx to #5 @jennyliang220
